### ISSUE TITLE
The `@as` attribute must be mandatory for application

### ISSUE THREAD

**Issue by yegor256** [objectionary/lints#676]
Let's make `@as` attribute mandatory of `<o/>` elements that stay inside `<o base="..">` (with the `@base` attribute).

Motivation: https://github.com/objectionary/phino/issues/200 and https://github.com/objectionary/jeo-maven-plugin/issues/1174

**Comment by yegor256** [comment]
@h1alexbel we should fix the parser, I believe

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#685](https://github.com/objectionary/lints/issues/685) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#685](https://github.com/objectionary/lints/issues/685) is solved here.
